consistency_algorithm: "Gossip"
gossip:
  port: 8081
  peers:
    - "localhost:8082"
    - "localhost:8083"
  node_id: "Node-1"
database:
  type: "mysql"
  host: "localhost"
  port: 3306
  user: "root"
  password: "123456"
  db_name: "echo_db"


